version: 2
jobs:
  build:
    docker:
     - image: circleci/openjdk:10.0.2-jdk-browsers
    working_directory: ~/CHASSIS
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - setup_remote_docker:
        version: 18.05.0-ce
        docker_layer_caching: true
    - add_ssh_keys:
        fingerprints:
          - "5f:9d:14:91:16:7c:39:92:67:55:6d:78:65:7e:f4:64"
    - run:
        name: Clone Services
        command: |
          GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@bitbucket.org:konradboniecki/password-management.git ~/passwordMgtRepo
          GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@bitbucket.org:konradboniecki/account-management.git ~/accountMgtRepo
          GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@bitbucket.org:konradboniecki/mail.git ~/mailRepo
          GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@bitbucket.org:konradboniecki/config-server.git ~/configServerRepo
          GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@bitbucket.org:konradboniecki/family-management.git ~/familyMgtRepo
    - checkout
#_______________________________________________________________

    - run:
        name: Install Updates and Maven
        command: |
          sudo apt-get update
          sudo apt-get install maven
    - run:
        name: Build and run tests
        command: |
          mvn clean install -B
    - store_test_results:
        paths:
        - chassis-test-tools/target/surefire-reports
    - store_artifacts:
        path: chassis-test-tools/target/surefire-reports/surefire-report.html
    - store_artifacts:
        path: chassis-test-tools/target/site/jacoco/
    - store_artifacts:
        path: chassis-test-tools/target/surefire-reports
#___________________________________________________SERVICE COMPATIBILITY
    - run:
        name: install stubs
        command: |
          cd ~/passwordMgtRepo
          mvn clean install -B -DskipTests=true
          cd ~/accountMgtRepo
          mvn clean install -B -DskipTests=true
          cd ~/mailRepo
          mvn clean install -B -DskipTests=true
          cd ~/familyMgtRepo
          mvn clean install -B -DskipTests=true
#_____________________________________________________________________________
    - run:
        name: Password management service compatibility validation
        command: |
          cd ~/passwordMgtRepo
          mvn clean install
    - store_artifacts:
        path: ~/passwordMgtRepo/target/surefire-reports
        destination: home/circleci/passwordMgtRepo/surefire-reports
#_____________________________________________________________________________
    - run:
        name: Account management service compatibility validation
        command: |
          cd ~/accountMgtRepo
          mvn clean install
    - store_artifacts:
        path: ~/accountMgtRepo/target/surefire-reports
        destination: home/circleci/accountMgtRepo/surefire-reports
#_____________________________________________________________________________
    - run:
        name: Mail service compatibility validation
        command: |
          cd ~/mailRepo
          mvn clean install
    - store_artifacts:
        path: ~/mailRepo/target/surefire-reports
        destination: home/circleci/mailRepo/surefire-reports
#_____________________________________________________________________________
    - run:
        name: Config server compatibility validation
        command: |
          cd ~/configServerRepo
          mvn clean install
    - store_artifacts:
        path: ~/configServerRepo/target/surefire-reports
        destination: home/circleci/configServerRepo/surefire-reports
    #_____________________________________________________________________________
    - run:
        name: Family management service compatibility validation
        command: |
          cd ~/familyMgtRepo
          mvn clean install
    - store_artifacts:
        path: ~/familyMgtRepo/target/surefire-reports
        destination: home/circleci/familyMgtRepo/surefire-reports
#_____________________________________________________________________________
    - run:
        name: Build and push image with chassis
        command: |
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            TAG=$CIRCLE_PROJECT_REPONAME-0.5-Stable
          fi
          if [ "$CIRCLE_BRANCH" != "master" ]; then
            TAG=$CIRCLE_PROJECT_REPONAME-0.5-Experimental
          fi
          docker build -t konradboniecki/budget:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push konradboniecki/budget:$TAG