version: 2
workflows:
  version: 2
  build-chassis-and-base-image:
    jobs:
      - build
      - build-base-image-approval:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
                - /feature.*/
      - build-base-image:
          requires:
            - build-base-image-approval
jobs:
  build:
    docker:
     - image: circleci/openjdk:11.0.3-jdk-stretch
    working_directory: ~/CHASSIS
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - add_ssh_keys:
        fingerprints:
          - "5f:9d:14:91:16:7c:39:92:67:55:6d:78:65:7e:f4:64"
    - run:
        name: Clone Services
        command: |
          GIT_PARAMS="-q --depth 1 --single-branch --branch develop"
          SSH_PARAMS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          GIT_SSH_COMMAND="ssh $SSH_PARAMS" git clone $GIT_PARAMS git@bitbucket.org:konradboniecki/config-server.git ~/configServerRepo
          GIT_SSH_COMMAND="ssh $SSH_PARAMS" git clone $GIT_PARAMS git@bitbucket.org:konradboniecki/password-management.git ~/passwordMgtRepo
          GIT_SSH_COMMAND="ssh $SSH_PARAMS" git clone $GIT_PARAMS git@bitbucket.org:konradboniecki/account-management.git ~/accountMgtRepo
          GIT_SSH_COMMAND="ssh $SSH_PARAMS" git clone $GIT_PARAMS git@bitbucket.org:konradboniecki/mail.git ~/mailRepo
          GIT_SSH_COMMAND="ssh $SSH_PARAMS" git clone $GIT_PARAMS git@bitbucket.org:konradboniecki/family-management.git ~/familyMgtRepo
          GIT_SSH_COMMAND="ssh $SSH_PARAMS" git clone $GIT_PARAMS git@bitbucket.org:konradboniecki/budget-management.git ~/budgetMgtRepo
          GIT_SSH_COMMAND="ssh $SSH_PARAMS" git clone $GIT_PARAMS git@bitbucket.org:konradboniecki/mvc.git ~/mvcRepo
    - checkout
    - run:
        name: Build and run tests
        command: |
          mvn clean install -s .circleci/settings.xml -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - store_test_results:
        path: chassis-test-tools/target/surefire-reports
    - store_artifacts:
        path: chassis-test-tools/target/surefire-reports/surefire-report.html
    - store_artifacts:
        path: chassis-test-tools/target/site/jacoco/
    - store_artifacts:
        path: chassis-test-tools/target/surefire-reports
#___________________________________________________SERVICE COMPATIBILITY
    - run:
        name: (1/7) Config server compatibility validation
        command: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          cd ~/configServerRepo
          echo "========Injecting Chassis version $VERSION========"
          mvn versions:update-parent "-DparentVersion=[$VERSION]" -DallowSnapshots=true -s /home/circleci/CHASSIS/.circleci/settings.xml
          mvn test -s /home/circleci/CHASSIS/.circleci/settings.xml -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - store_artifacts:
        path: ~/configServerRepo/target/surefire-reports
        destination: home/circleci/configServerRepo/surefire-reports
#_____________________________________________________________________________
    - run:
        name: (2/7) Password management service compatibility validation
        command: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          cd ~/passwordMgtRepo
          echo "========Injecting Chassis version $VERSION========"
          mvn versions:update-parent "-DparentVersion=[$VERSION]" -DallowSnapshots=true -s /home/circleci/CHASSIS/.circleci/settings.xml
          mvn test -s /home/circleci/CHASSIS/.circleci/settings.xml -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - store_artifacts:
        path: ~/passwordMgtRepo/target/surefire-reports
        destination: home/circleci/passwordMgtRepo/surefire-reports
#_____________________________________________________________________________
    - run:
        name: (3/7) Account management service compatibility validation
        command: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          cd ~/accountMgtRepo
          echo "========Injecting Chassis version $VERSION========"
          mvn versions:update-parent "-DparentVersion=[$VERSION]" -DallowSnapshots=true -s /home/circleci/CHASSIS/.circleci/settings.xml
          mvn test -s /home/circleci/CHASSIS/.circleci/settings.xml -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - store_artifacts:
        path: ~/accountMgtRepo/target/surefire-reports
        destination: home/circleci/accountMgtRepo/surefire-reports
#_____________________________________________________________________________
    - run:
        name: (4/7) Mail service compatibility validation
        command: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          cd ~/mailRepo
          echo "========Injecting Chassis version $VERSION========"
          mvn versions:update-parent "-DparentVersion=[$VERSION]" -DallowSnapshots=true -s /home/circleci/CHASSIS/.circleci/settings.xml
          mvn test -s /home/circleci/CHASSIS/.circleci/settings.xml -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - store_artifacts:
        path: ~/mailRepo/target/surefire-reports
        destination: home/circleci/mailRepo/surefire-reports
#_____________________________________________________________________________
    - run:
        name: (5/7) Family management service compatibility validation
        command: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          cd ~/familyMgtRepo
          echo "========Injecting Chassis version $VERSION========"
          mvn versions:update-parent "-DparentVersion=[$VERSION]" -DallowSnapshots=true -s /home/circleci/CHASSIS/.circleci/settings.xml
          mvn test -s /home/circleci/CHASSIS/.circleci/settings.xml -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - store_artifacts:
        path: ~/familyMgtRepo/target/surefire-reports
        destination: home/circleci/familyMgtRepo/surefire-reports
#_____________________________________________________________________________
    - run:
        name: (6/7) Budget management service compatibility validation
        command: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          cd ~/budgetMgtRepo
          echo "========Injecting Chassis version $VERSION========"
          mvn versions:update-parent "-DparentVersion=[$VERSION]" -DallowSnapshots=true -s /home/circleci/CHASSIS/.circleci/settings.xml
          mvn test -s /home/circleci/CHASSIS/.circleci/settings.xml -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - store_artifacts:
        path: ~/budgetMgtRepo/target/surefire-reports
        destination: home/circleci/budgetMgtRepo/surefire-reports
#_____________________________________________________________________________
    - run:
        name: (7/7) MVC service compatibility validation
        command: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          cd ~/mvcRepo
          echo "========Injecting Chassis version $VERSION========"
          mvn versions:update-parent "-DparentVersion=[$VERSION]" -DallowSnapshots=true -s /home/circleci/CHASSIS/.circleci/settings.xml
          mvn test -s /home/circleci/CHASSIS/.circleci/settings.xml -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - store_artifacts:
        path: ~/mvcRepo/target/surefire-reports
        destination: home/circleci/mvcRepo/surefire-reports
    - run:
        name: Deploy artifacts to nexus
        command: |
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            mvn deploy -s .circleci/settings.xml -DskipTests=true
          fi
          if [ "$CIRCLE_BRANCH" == "develop" ]; then
            mvn deploy -s .circleci/settings.xml -DskipTests=true
          fi
  build-base-image:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: false
      - add_ssh_keys:
          fingerprints:
            - "5f:9d:14:91:16:7c:39:92:67:55:6d:78:65:7e:f4:64"
      - checkout
      - run:
          name: Build and push docker image
          command: |
            TAG=java-base-image-$CIRCLE_BUILD_NUM
            docker build -t konradboniecki/budget:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push konradboniecki/budget:$TAG
