# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [ created ]
  workflow_dispatch:

env:
  MVN_CONFIG: -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests=true ${{ env.MVN_CONFIG }}
      - name: print
        run: |
          echo $GITHUB_WORKSPACE/.github/settings.xml
          echo ${{ github.workspace }}
          ls $GITHUB_WORKSPACE/.github/
      - name: Publish to GitHub Packages Apache Maven
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: mvn deploy -s $GITHUB_WORKSPACE/.github/settings.xml ${{ env.MVN_CONFIG }} -Dtoken=${{ secrets.PUBLISH_TOKEN }}
